config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do 
    root 'categories#index', as: :authenticated_root
  end

  unauthenticated do 
    root 'public#splash', as: :unauthenticated_root
  end

  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy, :show] do 
    resources :expenses, only: [:new, :create, :destroy] 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
  validates :icon, presence: true

  def total_expense
    expenses.sum(:amount)
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validate :belongs_to_a_category

  private

  def belongs_to_a_category
    return unless category_ids.empty?

    errors.add(:category_ids, 'should have at least one category')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :expenses, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.includes(:expenses)
    @unique_expenses = current_user.expenses.joins(:categories).distinct
    @total_expense = @unique_expenses.map(&:amount).sum
  end

  def show
    @category = current_user.categories.includes(:expenses).find(params[:id])
    @expenses = @category.expenses.sort { |a, b| b.updated_at <=> a.updated_at }
    @total_amount = @expenses.map(&:amount).sum
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:success] = 'New category has been created.'
      redirect_to categories_path
    else
      error = @category.errors.full_messages[0]
      flash[:error] = "#{error}. Please try again."
      redirect_to new_category_path
    end
  end

  def edit
    @category = current_user.categories.find(params[:id])
  end

  def update
    @category = current_user.categories.find(params[:id])
    return unless @category.update(category_params)

    flash[:success] = "#{@category.name} has been updated."
    redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    flash[:success] = "#{@category.name} category has been deleted."
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def new
    @categories = current_user.categories
    @category = @categories.select { |i| i.id == params[:category_id].to_i }[0]
    @expense = Expense.new
  end

  def create
    @category = Category.find(params[:category_id])
    @expense = Expense.new(expense_params)
    @expense.author = current_user

    if @expense.save
      flash[:success] = "You've just added a new expense."
      redirect_to category_path(@category)
    else
      error = @expense.errors.full_messages[0]
      flash[:error] = "#{error}. Please try again."
      redirect_to new_category_expense_path(@category)
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @expense = Expense.find(params[:id])
    @expense.destroy

    flash[:success] = 'Expense item has been removed.'
    redirect_back(fallback_location: authenticated_root_path)
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def splash; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/_expense_item.html.erb
<div class="item-card">
    <div class="item-meta">
        <div class="item-icon">💸</div>
        <div class="item-group">
            <h3 class="item-name"><%= expense.name %></h3>
            <p class="item-data">
                <%= expense.updated_at.to_datetime.strftime("%B %d, %Y") %>
            </p>
        </div>
    </div>
    <div class="item-group">
        <p class="item-value">
            <%= number_to_currency(expense.amount) %>
        </p>
        <%= button_to content_tag(:i, "", class: "fa-solid fa-square-minus") + "Remove", category_expense_path(category, expense), method: :delete, class: 'cat-action del-btn' %>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>

  <div class="form-group">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, placeholder: "Categroy name", required: true, class: 'form-control' %>
  </div>

  <% options = [  ["🍔 Food and dining", "🍔"],
    ["🛒 Groceries", "🛒"],
    ["🚗 Tranportation", "🚗"],
    ["🐶 Pet expenses", "🐶"],
    ["📚 Book", "📚"],
    ["💻 Electronics", "💻"],
    ["🎁 Gift", "🎁"],
    ["🏠 Housing", "🏠"],
    ["🏥 Health", "🏥"],
    ["🎬 Entertainment", "🎬"],
    ["👔 Clothing", "👔"],
    ["🎓 Education", "🎓"],
    ["🧾 Others", "🧾"],
  ] %>


  <div class="form-group">
    <%= form.label :icon %>
    <%= form.select :icon, options_for_select(options, selected: category.icon), {prompt: "Select an icon" }, {class: 'form-control'} %>
  </div>


  <%= form.submit "#{editing ? 'Update' : 'Create'} Category", class: 'btn btn-primary' %>

  <%= link_to 'Cancel', categories_path, class: "btn btn-outline" %>
<% end %>

app/views/categories/_item.html.erb
<%= link_to category_path(category), class: "item-card" do %> 
    <div class="item-meta">
        <div class="item-icon"><%= category.icon %></div>
        <div class="item-group">
            <h3 class="item-name"><%= category.name %></h3>
            <p class="item-data"><%= pluralize(category.expenses.length, "Entry") %></p>
        </div>
    </div>
    <div class="item-group">
        <p class="item-value">
            <%= number_to_currency(total) %>
        </p>
    </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/header', back_link: categories_path, title: "Edit Category" %>
<section class="container">
    <div class="form-container">
        <%= render 'form', category: @category, editing: true %>
    </div>
</section>

app/views/categories/index.html.erb
<%= render 'shared/header', title: "Categories", back_link: false %>
<section class="container">
<div class="total-header">
    <% expense_count = @unique_expenses.size %>
    <p>Spending: <%= number_to_currency(@total_expense) %></p>
    <p>Unique <%= expense_count == 1 ? "Entry: " : "Entries: " %><%= expense_count %></p>
</div>
<% if @categories.empty? %>
    <div class="note-container">
        <h2 class="note-title">No Categories Yet!</h2> 
        <p class="note-text">Categories are an essential part of this app. They help you track your expenses by grouping them into different areas of your life, such as 🏠 housing, 🍔 food, and 🎬 entertainment. To get started, create a category for each area where you spend money. <br/>Happy budgeting!</p>
    </div>
<% else %>
    <div class="items-container">
        <% @categories.each do |category| %>
            <%= render 'item', category: category, 
            total: @unique_expenses.map {|i| category.expenses.include?(i) ? i.amount : 0 }.sum %>
        <% end %>
    </div>
<% end %>

<div class="action-container">
    <%= link_to "Add Category", new_category_path, class: "action-button" %>
</div>
</section>

app/views/categories/new.html.erb
<%= render 'shared/header', back_link: categories_path, title: "New Category" %>
<section class="container">
    <div class="form-container">
        <%= render 'form', category: @category, editing: false %>
    </div>
</section>

app/views/categories/show.html.erb
<%= render 'shared/header', title: "#{@category.icon} #{@category.name}", back_link: categories_path %>
<section class="container">
<div class="total-header">
    <p>Spending: <%= number_to_currency(@total_amount) %></p>
    <p><%= @expenses.size == 1 ? "Entry: " : "Entries: " %><%= @expenses.size %></p>
</div>
<div class="category-actions">
    <%= link_to content_tag(:i, "", class: "fa-solid fa-pencil")+ "Edit Category", edit_category_path(@category), class: 'cat-action edit-btn' %>
    <%= button_to content_tag(:i, "", class: "fa-solid fa-trash")+ "Delete Category", category_path(@category), method: :delete, class: 'cat-action del-btn' %>
</div>
<% if @expenses.empty? %>
    <div class="note-container">
        <h2 class="note-title">No Expenses Yet!</h2> 
        <p class="note-text">You haven't added any expenses to this category yet. Click the "Add Expense" button below and enter the details of your expense to track your spending.</p>
    </div>
<% else %>
    <div class="items-container">
        <% @expenses.each do |expense| %>
            <%= render 'expense_item', category: @category, expense: expense %>
        <% end %>
    </div>
<% end %>

<div class="action-container">
    <%= link_to "Add Expense", new_category_expense_path(@category), class: "action-button" %>
</div>
</section>

app/views/expenses/_form.html.erb
<%= form_with model: [@category, @expense] do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter expense name", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: 'form-control', placeholder: "Enter amount in USD", required: true, min: 0 %>
  </div>

  <div class="form-group">
    <%= form.label :category_ids, "Categories" %>
    <div class="check-boxes">
      <%= form.collection_check_boxes :category_ids, @categories, :id, :name, {checked: @category.id} do |b| %>
        <div class="form-check">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
  </div>

  <%= form.submit "Add Expense", class: 'btn btn-primary' %>
  <%= link_to 'Cancel', category_path(@category), class: 'btn btn-outline' %>
<% end %>

app/views/expenses/new.html.erb
<%= render 'shared/header', back_link: category_path(@category), title: "New Expense" %>
<section class="container">
    <% if flash[:alert].present? %>
        <div class="alert alert-danger">
            <strong>Error:</strong> <%= flash[:alert] %>
        </div>
    <% end %>
    <div class="form-container">
        <%= render 'form' %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinTrackr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&family=Rubik:wght@300;400;500;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
<% end %>
<% flash.each do |key, value| %>
  <% if key == "success" %>
    <div class="alert alert-success"><strong>Success! </strong><%= value %></div>
  <% elsif key == "error" %>
    <div class="alert alert-danger"><strong>Error: </strong><%= value %></div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="main-header">
    <% if back_link %>
        <%= link_to content_tag(:i, "", class: "fa-sharp fa-solid fa-arrow-left"), back_link, class: "icon-btn" %>
    <% else %>
        <button type="button" class="icon-btn" onclick="toggleSideMenu();"><i class="fa fa-bars"></i></button>
    <% end %>
    <h1><%= title.upcase %></h1>
    <% if user_signed_in? %>
        <%= button_to  content_tag(:i, "", class: "fa-solid fa-right-from-bracket"), destroy_user_session_path, method: :delete, class: "icon-btn text-right" %>
    <% elsif controller_name != 'sessions' %>
        <%= link_to content_tag(:i, "", class: "fa-solid fa-right-to-bracket"), new_user_session_path, class: "icon-btn text-right" %>
    <% else %>
        <%= link_to content_tag(:i, "", class: "fa-solid fa-user-plus"), new_user_registration_path, class: "icon-btn text-right" %>
    <% end %>
</header>

<%= render 'shared/alert' %>

<% if user_signed_in? %>
<div class="side-menu">
  <div class="side-header">
    <button type="button" class="icon-btn" onclick="toggleSideMenu();"><i class="fa-solid fa-xmark"></i></button>
    <h2 class="brand">CoinTrackr</h2>
  </div>
  <div class="profile-container">
    <div class="user-icon">
      <i class="fa-solid fa-user "></i>
    </div>
    <p class="user-name"><%= current_user.name %></p>
  </div>

  <div class="side-actions">
    <%= link_to edit_user_registration_path, class: "action-group" do %>
      <div class="action-icon">
        <i class="fa-solid fa-address-book"></i>
      </div>
        <p>Account Setting</p>
    <% end %>

    <%= link_to new_category_path, class: "action-group" do %>
      <div class="action-icon">
        <i class="fa-solid fa-folder-plus"></i>
      </div>
        <p>Create Category</p>
    <% end %>

    <%= link_to "https://github.com/IndieCoderMM/coin-trackr", class: "action-group", target: "_blank" do %>
      <div class="action-icon">
        <i class="fa-solid fa-file-code"></i>
      </div>
        <p>View Project</p>
    <% end %>

    <%= link_to "https://github.com/IndieCoderMM", class: "action-group", target: "_blank" do %>
      <div class="action-icon">
        <i class="fa-brands fa-github"></i>
      </div>
        <p>Author Profile</p>
    <% end %>
  </div>
</div>
<% end %>

<script>
function toggleSideMenu() {
  const menu = document.querySelector(".side-menu");
  menu.classList.toggle('show');
}
</script>